spring.application.name=smcp
spring.security.oauth2.client.registration.blizzard-cc.client-id=${BLIZZARD_CLIENT_ID}
spring.security.oauth2.client.registration.blizzard-cc.client-secret=${BLIZZARD_CLIENT_SECRET}
spring.security.oauth2.client.registration.blizzard-cc.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.blizzard-cc.scope=wow.profile
spring.security.oauth2.client.provider.blizzard-cc.token-uri=https://oauth.battle.net/token


